# trigger this pipeline if there's a PR to any of these branches
pr:
- develop
- qa

# trigger this pipeline if there's merge to any of these branches
trigger:
- develop
- qa

variables:
  # Common variables
  - template: variables/variables.yml@templates
  # Git repository name
  - name: repoName
    value: 'spring-petclinic'
  # Docker project image version.
  - name: version
    value: '1.0.0'
  # Add build ID for unique image tags
  - name: buildId
    value: $(Build.BuildId)

resources:
  repositories:
  - repository: templates
    type: git
    endpoint: danielhg1285
    name: danielhg1285/pipeline-templates
    ref: refs/heads/main

pool:
   vmImage: 'ubuntu-latest'

stages:

- stage: BuildPushDockerImage
  displayName: Compilado de Imagen Docker
  jobs:
  - job: test
    steps:
    - task: Maven@4
      inputs:
        mavenPomFile: 'pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.11'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        goals: 'package'